### PR TITLE
Add `Execute()` extension method to simplify usage with EnumInstructions

### PR DESCRIPTION
**Pull request by seveneleven**

### CODE REVIEW

**Review by 1nf0rmagician — APPROVED** [review]

**Comment by Toxantron** [comment]
The callback is not invoked and all existing methods use `int result` and `typeof(TEnum)`. Do we need a generic extension or is it sufficient to restore that signature?

**Comment by 1nf0rmagician** [comment]
The motivation was sparked when I wrote the migration guide, specifically these lines:
```c#
// MORYX 6
VisualInstructor.Execute("Some Title", someInstructions, new EnumInstructionResult(typeof(AskRotationPermissionResult), SomeAction));

// MORYX 8
VisualInstructor.Execute("Some Title", someInstructions, EnumInstructionResult.PossibleResults(typeof(AskRotationPermissionResult)),
  param => SomeAction(EnumInstructionResult.ResultToEnumValue(typeof(ArticleMountingStrategy), param.Result)));
```

The generic extension should drastically simplify this solid two-liner of a method call 😅

**Comment by Toxantron** [comment]
Anything left here and can we merge into `dev`?

**Comment by 1nf0rmagician** [comment]
I like it and would merge it 😊

**Comment by Toxantron** [comment]
Well, as it turns out: This never compiled...

**Comment by 1nf0rmagician** [comment]
But why could you merge it, github should have prevented that since the build step failed...

**Comment by Toxantron** [comment]
Well, since there was no updated approval, I had to merge with admin priviliges anyway - which also overwrites the CI build check.

**Pull request merged**
